### PR TITLE
Update VulkanSDK to 1.1.121.2

### PR DESCRIPTION
**Pull request by emulationchannel**

### CODE REVIEW

**Comment by emulationchannel** [comment]
@dracc update SDL 2.0.10 testing https://github.com/bincrafters/conan-sdl2

**Comment by dracc** [comment]
@emulationchannel Yes, what you're trying to accomplish is very clear. What I'm questioning is merely the commit history - what looks like duplicated commits and multiple commits touching the same file with the same exact commit messages.

**Comment by emulationchannel** [comment]
ok sorry

**Comment by emulationchannel** [comment]
build failed  (60 minutes).

**Comment by emulationchannel** [comment]
closed don't scare opened again later so i did what was said by friend @dracc

**Pull request closed without merging**
