### PR TITLE
opengl: Transform feedback fixes.

### PR DESCRIPTION
**Pull request by achurch**
Based on #316.

### CODE REVIEW

**Comment by JohnGodgames** [comment]
There is a performance boost with this PR.Check Barbie http://imgur.com/a/WTkGV

**Comment by Adubbz** [comment]
Looks like these changes break NES Remix again. Like before, Mario stops flashing and the screen doesn't update. Here's the log http://hastebin.com/raw/juwocusaru (although I'm guessing you'll probably want other details, let me know what you'd like)

The score/timer counters also don't update but I believe that issue is linked to an earlier commit.

**Comment by achurch** [comment]
>Looks like these changes break NES Remix again.

Can you identify which of the changes causes the problem?

**Comment by Adubbz** [comment]
https://github.com/decaf-emu/decaf-emu/pull/336/commits/1ef94f79b6ec1e63685cbbdb0ead17d88c599b2b seems to be the culprit

**Comment by achurch** [comment]
Okay, that change isn't part of this PR - it's part of #316. There have been additional changes there, so please test against #316 and see if it's fixed.

**Comment by exjam** [comment]
Remember this was the one that used tiling apertures, the invalidates look like this:

[59:43.432112 debug:w108] 0x02018998 GX2Invalidate(2, 0x22829800, 0x0003C000)
[59:43.433332 debug:w108] 0x0215C894 GX2Invalidate(64, 0x20776800, 0x000001C0)
[59:43.433399 debug:w108] 0x0215C894 GX2Invalidate(64, 0x207CA740, 0x00000070)
[59:43.433426 debug:w108] 0x0215C894 GX2Invalidate(64, 0x207CB5C0, 0x00000070)
[59:43.484422 debug:w108] 0x02018988 GX2Invalidate(64, 0xB0000000, 0x0003C000)
[59:43.484476 debug:w108] 0x02018998 GX2Invalidate(2, 0x22829800, 0x0003C000)
[59:43.485791 debug:w108] 0x0215C894 GX2Invalidate(64, 0x20776C60, 0x000001C0)
[59:43.485881 debug:w108] 0x0215C894 GX2Invalidate(64, 0x207CABA0, 0x00000070)
[59:43.485966 debug:w108] 0x0215C894 GX2Invalidate(64, 0x207CBA20, 0x00000070)
[59:43.532413 debug:w108] 0x02018988 GX2Invalidate(64, 0xB0000000, 0x0003C000)

**Comment by Adubbz** [comment]
Oh, sorry, my bad. I thought this PR was an updated version of that combined with a bunch of other changes. I'll try that now.

**Comment by achurch** [comment]
@exjam Ah, good point, I'd forgotten about that. In that case we may need to bring back the change to translate aperture addresses to physical addresses, see https://github.com/achurch/decaf-emu/commit/65be77e1908e4e96b4417513ecef7a3333b51992

**Comment by exjam** [comment]
Huh.. did that code never get merged? I thought we did. We definitely do need it to get that CPU flush for the tiling aperture for NES Remix.

[05:41.081397 debug:w108] Allocate Tiling Aperture for surface->image = 0x22829800 surface->size = 0x3C000
[05:41.081708 debug:w108] 0x02018988 GX2Invalidate(64, 0xB0000000, 0x0003C000)
[05:41.081752 debug:w108] 0x02018998 GX2Invalidate(2, 0x22829800, 0x0003C000)

**Comment by achurch** [comment]
I think @brett19 said something about wanting to rewrite the aperture code so he didn't want to add more changes to the existing code, but I don't recall for sure.

**Comment by Adubbz** [comment]
Applying that patch whilst using #316 doesn't appear to do anything

**Comment by exjam** [comment]
That's because 
```
   if (mode & GX2InvalidateMode::CPU) {
      coreinit::DCFlushRange(buffer, size);
   }
```

But we only update addr and not buffer.
```
      // Invalidate the entire aperture (since the data layout is different)
      addr = physBase;
      size = apertureSize;
```

Changing the DCFlushRange to use addr would fix the issue:
```
   if (mode & GX2InvalidateMode::CPU) {
      coreinit::DCFlushRange(mem::translate(addr), size);
   }
```

**Comment by achurch** [comment]
Ooh, good catch. @Adubbz, does that fix things for you?

**Comment by Adubbz** [comment]
:+1: Indeed it does

**Comment by exjam** [comment]
Merged.

da35ee946169bceef1fd6b0de3b416a5bab6f875
ce4d631280145f677f5dd27ecba4bf21b973bbac
a8064e43d5239b907ec1e1616b20aa78c6e1f9b5
d3d3727122642caf5e4129e3cbf2e19b995b88d7
cfb8ad034f2925394da1c1daee8e90e595094504

**Pull request closed without merging**
