### PR TITLE
Fix assertion failure when changing cores due to KC instruction.

### PR DESCRIPTION
**Pull request by achurch**

### CODE REVIEW

**Comment by brett19** [comment]
This is actually not a safe fix.  When we switch cores, we should be restoring the CoreReg's state exactly as it was before the core switch.  This means that the assertion should still hold, providing that the core pointer has been updated to reference the new core.  If this assertion does not hold through a scheduler core change, it indicates that the restoral is not being performed accurately and a bug is present somewhere else.

**Comment by achurch** [comment]
Fair enough. The core->cia assignment earlier in the function was explicitly listed as "for debugging purposes", so I assumed KC was an exceptional case with respect to that as well, but I'll dig deeper.

**Comment by achurch** [comment]
Thanks for making me look harder. The cause of the actual case I found was not a core switch but a call to PPC code from an HLE function (specifically ghs_mtx_init), in turn called from step_one() via a kc instruction. It looks like the correct solution is to save and restore cia along with nia in wfunc_ptr::operator() - PTAL.

**Comment by achurch** [comment]
Can't seem to reopen this after pushing the fixed change, so I've opened a separate request. Sorry for the update spam.

**Pull request closed without merging**
