### PR TITLE
opengl: Cache additional GL state data.

### PR DESCRIPTION
**Pull request by achurch**
FYI, this gives me a performance boost of about 15% on the Xenoblade title screen.

(One of these days I just know I'm going to type Xenogears instead of Xenoblade...)

### CODE REVIEW

**Comment by achurch** [comment]
Added suppression of glCheckFramebufferStatus() when unnecessary (per the GL spec). The additional improvement isn't a lot, but I do see FPS peak a bit higher than before so probably still worth it.

**Comment by brett19** [comment]
Conflicts now.  Needs a rebase.

**Comment by achurch** [comment]
Rebased.

**Comment by achurch** [comment]
Rebased again.

**Pull request merged**
