### PR TITLE
common: Add POSIX support for illegal instruction exceptions.

### PR DESCRIPTION
**Pull request by achurch**

### CODE REVIEW

**Comment by brett19** [comment]
Has anyone every told you they loved you @achurch?  Because we love you.  Thanks 😍

**Comment by achurch** [comment]
Haha, just trying to be useful (:

**Comment by brett19** [comment]
You should jump on IRC for a quick discussion on JIT verify when you get a chance.

**Comment by brett19** [comment]
Merged as a3148006

**Pull request closed without merging**
