### PR TITLE
opengl: Simplify locking.

### PR DESCRIPTION
**Pull request by achurch**

### CODE REVIEW

**Comment by brett19** [comment]
This removes one of the locks entirely, which leaves a bunch of shared state without any kind of mutex protecting it.

**Comment by achurch** [comment]
What part of the state is actually shared, except the new task stuff?

**Comment by brett19** [comment]
All of the state inside of the OpenglDriver

**Comment by achurch** [comment]
That's not an answer. :P All the interesting stuff happens via PM4 commands which is all on the same thread, so there's nothing it needs to be locked against.

**Comment by brett19** [comment]
The list of buffers for instance.  The specific case thats going to be relevant is knowing the information about a surface to decide whether we need to do a texture download from copySurface.

**Pull request closed without merging**
