### PR TITLE
opengl: Use common logic for uniform, attribute, and feedback buffers.

### PR DESCRIPTION
**Pull request by achurch**
This gives me a solid ~30% speed increase in Xenoblade.

### CODE REVIEW

**Comment by achurch** [comment]
Rebased on top of the locking changes.

**Comment by exjam** [comment]
Sorry can you rebase this again please :fire: ! Thanks :+1:

**Comment by brett19** [comment]
Could you also split this into two PRs?  We want to accept transform feedback, but need to do a little work on the other part.

**Comment by exjam** [comment]
Actually on further though invalidating tiling apertures is going to require some more work because of how we implement it.

On hardware a tiling aperture is a virtual memory map over the same physical memory of the tiled texture. That is impossible for us to implement so we hack around it by copying and untiling the texture to tiling aperture memory on GX2AllocateTilingApertureEx, and copying and retiling it back to the original memory on GX2FreeTilingAperture. This will not work if the GPU picks up the invalidate before the original texture memory has been updated by GX2FreeTilingAperture.  Or for example if a game never actually frees an aperture and just keeps reusing it.

Really the best fix would to be to forward through the untiled aperture memory all the way through to the GPU so we don't have to do the retile -> untile -> upload stage.

I think for now maybe just remove the tiling aperture invalidation code from this PR and we can revisit it at a later point.

**Comment by achurch** [comment]
Rebased and removed aperture stuff, PTAL.

**Pull request merged**
