### PR TITLE
jit: Implement JIT verifier.

### PR DESCRIPTION
**Pull request by achurch**

### CODE REVIEW

**Comment by brett19** [comment]
Can you rebase this onto master, and try to move as much stuff out of jit.cpp into something like jit_verify.cpp?  I actually really need this right now, would be awesome to get it merged.

**Comment by achurch** [comment]
Rebased. I've already written it so that most of the verification-specific logic is in jit_verify.cpp; what's left in jit.cpp is the code to interface to that.

**Comment by brett19** [comment]
`/jit/jit.cpp` gets an extra 150+ lines of code just to interface?  That's saddening.  Someday we will need to come up with some way to do cool JIT things without writing code throughout.

**Comment by brett19** [comment]
Is the tweaked prologue/epilogue supposed to go before or after this commit.  Or is it already closed?

**Comment by brett19** [comment]
Your rebase doesn't actually build haha.  Trying to fix it now.

**Comment by brett19** [comment]
Merged as bc1e5cb5

**Pull request closed without merging**
