### PR TITLE
Check vulkan extensions are available when creating device

### PR DESCRIPTION
**Pull request by Narann**
Before this commit, decaf was crashing, raising an `ErrorExtensionNotPresent` exception. This commit logs missing extensions before letting decaf quitting.

### CODE REVIEW

**Comment by Narann** [comment]
As I didn't discussed this before, it's more a starting point for discussing about it. It's how I see the correct way of doing it but some maybe have another perspective.

It's my first PR on decaf so feel free to point every possible missing point.

**Comment by Narann** [comment]
Here is the log:
```
[11:20:51.005968 info:decaf] Built on 2019-06-22T12:33:44Z from bdc2ac3b-dirty
[info] Target /home/narann/Downloads/fireplace-nx-wiiu/wiiu/apps/fireplace-nx-wiiu/fireplace.rpx
[info] Loaded config from /home/narann/.config/decaf/config.toml
[11:20:51.237196 error:sdl-vk] Missing extensions detected
[11:20:51.237227 error:sdl-vk]   VK_KHR_display_swapchain
[11:20:51.237236 error:sdl-vk]   VK_EXT_fragment_density_map
[11:20:51.237243 error:sdl-vk]   VK_EXT_hdr_metadata
[11:20:51.237250 error:decaf-cli] Failed to create Vulkan graphics window
[11:20:51.237258 error:decaf-cli] Failed to initialise Vulkan backend.
```

Maybe replace `Can't create device because of missing extensions:` instead of confusing `Missing extensions detected`.

**Comment by Narann** [comment]
Same problem:

```
Unpacking libglbinding-dev (3.1.0+571~ubuntu16.04.1) ...
dpkg: error processing archive /var/cache/apt/archives/libglbinding-dev_3.1.0+571~ubuntu16.04.1_amd64.deb (--unpack):
 trying to overwrite '/usr/include/KHR/khrplatform.h', which is also in package libegl1-mesa-dev:amd64 18.0.5-0ubuntu0~16.04.1
```

**Comment by exjam** [comment]
Looks good, thanks.

**Pull request merged**
