### PR TITLE
Debugger tweaks.

### PR DESCRIPTION
**Pull request by achurch**
A couple of debugger changes I found convenient, plus a workaround for being unable to select some unnamed threads.

### CODE REVIEW

**Comment by brett19** [comment]
👎  Do not merge.

**Comment by brett19** [comment]
The logic for 8c84387 actually already exists in the code, it just doesn't work on first activation of the debugger.  It should be trivial to fix rather than needing the whole change.

**Comment by brett19** [comment]
d7abed4 looks good, it's kind of strange because the hack I originally put in there (a bunch of spaces) actually lets it be selected, but then ImGui fails to actually detect clicks on it.

**Comment by achurch** [comment]
Re 8c84387, where is the logic? I didn't see any, which is why the changes to add it.

**Comment by brett19** [comment]
Hey @achurch, take a look at 1815f619.  I fixed the bug there.

**Comment by achurch** [comment]
That commit doesn't seem to exist.

**Comment by brett19** [comment]
Sorry.  Give me a few minutes.  It's on top of a bunch of other stuff I did which broke something important.

**Comment by brett19** [comment]
P.S. Do you have Google Hangouts/Skype?

**Comment by achurch** [comment]
Afraid not, no.

**Comment by brett19** [comment]
How do you communicate with the world! :D

**Comment by achurch** [comment]
E-mail. With a capital E and a hyphen. And get off my lawn! ;)

**Comment by achurch** [comment]
Sure, SGTM. Thoughts on the thread highlighting commit? I found that made it easier to keep track of which thread I was looking at.

**Comment by brett19** [comment]
I like the idea of that commit, I'm just not sure about how to present it, and I found the implementation a bit dirty to put it in temporarily till we can find a better solution.

**Comment by achurch** [comment]
Fair enough. I'll just keep using it locally until something better comes along.

**Comment by brett19** [comment]
8c84387 -> 911d8a56 (as discussed above, it just needed a minor fix)
d7abed4 -> 8bb82940 (rebased to the latest changes for you)

**Comment by brett19** [comment]
040e3fc -> 7adce872 (highlight active thread)

P.S.  Hope you don't mind that I kept you as the author in spite of making minor changes.  Figured I should give credit where it is due.

**Comment by achurch** [comment]
LGTM, and thanks, the credit is appreciated. (: I'm still getting some cases where the debugger doesn't stop on the right thread at a breakpoint, though -- I'll keep looking into that.
Also, nice work on the stack view! I'd actually just been thinking about making one myself.

**Pull request closed without merging**
