### PR TITLE
SDL Multi Window - Window for Screen and DRC

### PR DESCRIPTION
**Pull request by CallumCarmicheal**
Using the parameter "--display-mode popup" will split both the tv and
DRC (gamepad) into separate windows where they can be resized and/or moved
to another monitor for a multi-monitor experience.

* Thanks to @jroweboy for fixing the aspect ratio.

### CODE REVIEW

**Comment by VelocityRa** [comment]
Nice, but you commited a lot of code style stuff you shouldn't have (brace style changes, space changes).
I recommend `git gui` or a tool like Git Kraken to cherry pick lines to commit (or just fix/disable your auto formatting).

**Comment by CallumCarmicheal** [comment]
@VelocityRa I used the settings sent by exjam and used auto format, thought it was correct ;(

**Comment by XenonPK** [comment]
Hello, I have built a [package](https://build.opensuse.org/package/show/home:xenonpk/decaf-emu) with the changes introduced by this PR and noticed (in NES Remix 2) when the display is set to popup, with:

> decaf-sdl play /opt/emulated/Wii_U/NES\ Remix\ 2/ --display-mode popup --sound --jit --gpu-force-sync --gpu-debug

The output is a black screen with a bunch of opengl errors in the CLI. Without --gpu-force-sync it works as intended. OpenSUSE Tumbleweed with latest NVIDIA stable drivers.

[_2017-03-29_14-37.txt](https://github.com/decaf-emu/decaf-emu/files/879207/_2017-03-29_14-37.txt)

The default display mode works regardless, whether --gpu-force-sync is enabled or disabled.

**Comment by CallumCarmicheal** [comment]
@XenonPK I'll look into it, thanks for the heads up!

**Pull request closed without merging**
