### PR TITLE
swkbd: Fix format of string returned by GetInputFormString().

### PR DESCRIPTION
**Pull request by achurch**
Fixes Xenoblade name entry getting garbage characters.

### CODE REVIEW

**Comment by exjam** [comment]
We should be using char16_t!

http://en.cppreference.com/w/cpp/language/types

"char16_t - type for UTF-16 character representation, required to be large enough to represent any UTF-16 code unit (16 bits). It has the same size, signedness, and alignment as std::uint_least16_t, but is a distinct type."

**Comment by achurch** [comment]
I tried char16_t in the template but got compiler errors. If you can find a way around that, by all means use it.

We certainly _shouldn't_ use char16_t in the return type because, like uint_least16_t, it's allowed to be wider than 16 bits.

**Comment by exjam** [comment]
That's odd, http://en.cppreference.com/w/cpp/locale/codecvt_utf8_utf16 says "Elem - either char16_t, char32_t, or wchar_t", but yes I agree with you for the return type at least!

**Comment by achurch** [comment]
FWIW, here's the error:
```
/usr/bin/../include/c++/v1/locale:3888:43: error: cannot initialize a parameter
      of type 'intern_type *' (aka 'char16_t *') with an lvalue of type
      'wchar_t *'
                                          __to, __to_end, __to_nxt);
                                          ^~~~
/usr/bin/../include/c++/v1/locale:3799:17: note: in instantiation of member
      function 'std::__1::wstring_convert<std::__1::codecvt_utf8_utf16<char16_t,
      1114111, 0>, wchar_t, std::__1::allocator<wchar_t>,
      std::__1::allocator<char> >::from_bytes' requested here
        {return from_bytes(__str.data(), __str.data() + __str.size());}
                ^
src/libdecaf/src/modules/swkbd/swkbd_core.cpp:129:26: note: 
      in instantiation of member function
      'std::__1::wstring_convert<std::__1::codecvt_utf8_utf16<char16_t, 1114111,
      0>, wchar_t, std::__1::allocator<wchar_t>, std::__1::allocator<char>
      >::from_bytes' requested here
   auto wide = converter.from_bytes(sInputBuffer);
                         ^
/usr/bin/../include/c++/v1/__locale:1022:28: note: passing argument to parameter
      '__to' here
              intern_type* __to, intern_type* __to_end, intern_type*& __...
                           ^
```
It looks like maybe the "w" in "wstring_convert" is the culprit, but there doesn't seem to be a "u16string_convert" to go with u16string, so I dunno. I admit my eyes tend to glaze over whenever I see STL template error spam...

**Comment by exjam** [comment]
Merged as 6bc50065c420565fca044e0e65d248f47e2de6aa

**Pull request closed without merging**
